# Generated by Django 5.1.6 on 2025-04-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_golfers',
            field=models.ManyToManyField(blank=True, related_name='fans', to='myapp.golfer'),
        ),
    ]
