# Generated by Django 5.1.6 on 2025-04-08 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_favorite_golfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsersFavoriteGolfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.golfer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'all_users_favorite_golfers',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_golfers',
            field=models.ManyToManyField(blank=True, related_name='fans', through='myapp.AllUsersFavoriteGolfers', to='myapp.golfer'),
        ),
    ]
